// What is HTTP?
/*
HTTP stands for Hyper Text Transfer Protocol. It is a method of transferring data across the 
internet from one endpoint to another.
*/

// What is a URL?
/*
URL stands for Universal Resource Locator. It is an address that leads to a specific endpoint on a server.
*/

// What is DNS?
/*
DNS stands for Domain Name System. It is a system that translates domain names into IP adresses 
that machines can understand.
*/

// What is a query string?
/*
A query string is an optional addendum to a URL that will often be used to search
on an endpoint, provided the functionality exists on the endpoint in question.
*/

// What are two HTTP verbs and how are they different?
/*
GET - retrieves data from an endpoint only.
POST - can retreive and modify data at an endpoint.
*/

// What is an HTTP request?
/*
An HTTP request is a stream of data sent to an endpoint whose purpose is to provide information needed
to send an appropriate response of data.
*/

// What is an HTTP response?
/*
An HTTP response is a stream of data generated by a request.
*/

// What is an HTTP header? Give a couple examples of request and response headers you have seen.
/*
An HTTP header is a type of meta data that can be used in a request or response.
Accept-Langauge is the human language that will be requested or responded with.
Cookie is the cached cookies for a given website.
*/

// What are the processes that happen when you type “http://somesite.com/some/page.html” into a browser?
/*
An HTTP request is sent to the server, evaluated, and an appropriate response is sent back.
*/

// curl -X GET https://icanhazdadjoke.com/search?term=pirate

// dig https://icanhazdadjoke.com

$(
    $("button").on("click", function() {
        console.log("sending request...")
        axios.post("localhost:8000");
    })
)